### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Daotin** [fe-captain/front-end-knowledge#2]
1、如何隐藏滚动条？ https://juejin.im/post/5a6046dbf265da3e253c3534

**Comment by Daotin** [comment]
2、图片宽高自适应

```css
.imgBox {
    width: 70px;
    height: 70px;
    img {
        max-width: 100%;
        max-height: 100%;
    }
}
```
